### ISSUE TITLE
Space between numbers and operators 

### ISSUE THREAD

**Issue by gozeloglu** [evylang/pratt#1]
Hi @juliaogris ,

This tool seems pretty nice. I tried in my local environment. The problem that I see is that if there is no exactly 1-space between operator(s) and number(s), it panics or doesn't execute the expression. You are splitting given string by `" "`(empty string with 1 char) and it limits the user. I am leaving the line:
https://github.com/evy-lang/pratt/blob/a8c1f51d271bc8b3cb7413164a721ebe6aa0857a/main.go#L40
I think this part should be refactored. Maybe a new helper function can be implemented for splitting and cleaning the string or regex can be used. I'd choose to implement a helper function because regex can be tricky and less understandable. 

Also, I am leaving the expressions that I tried and the results that I got:

```shell
$ pratt '2+4*12*2*442'   
2+4*12*2*442 # does nothing

$ pratt -r '2 + 4 * 12 * 2 *442' 
panic: no more tokens

goroutine 1 [running]:
main.(*tokens).cur(...)
	/Users/gokhanozeloglu/personal/pratt/main.go:49
main.(*tokens).next(...)
	/Users/gokhanozeloglu/personal/pratt/main.go:55
main.parseR(0x140000a2d08?)
	/Users/gokhanozeloglu/personal/pratt/main.go:91 +0x158
main.parseR(0x140000a2d01?)
	/Users/gokhanozeloglu/personal/pratt/main.go:96 +0x98
main.parseR(0x140000bc000?)
	/Users/gokhanozeloglu/personal/pratt/main.go:96 +0x98
main.parseR(0x147191b01?)
	/Users/gokhanozeloglu/personal/pratt/main.go:96 +0x98
main.parseR(0x16fa439f1?)
	/Users/gokhanozeloglu/personal/pratt/main.go:96 +0x98
main.main()
	/Users/gokhanozeloglu/personal/pratt/main.go:24 +0x174

$ pratt '2 +         4 * 12 * 2 * 442 / 12'
panic: no precedence for 

goroutine 1 [running]:
main.(*tokens).curPrec(...)
	/Users/gokhanozeloglu/personal/pratt/main.go:63
main.parse(0x14000104f08, 0x2)
	/Users/gokhanozeloglu/personal/pratt/main.go:112 +0x2cc
main.parse(0x14000104f08, 0x0)
	/Users/gokhanozeloglu/personal/pratt/main.go:115 +0xa0
main.main()
	/Users/gokhanozeloglu/personal/pratt/main.go:28 +0x168

$ pratt '2+ 4*12 *2*442/12'
panic: no precedence for 4*12

goroutine 1 [running]:
main.(*tokens).curPrec(...)
	/Users/gokhanozeloglu/personal/pratt/main.go:63
main.parse(0x14000070f08, 0x0)
	/Users/gokhanozeloglu/personal/pratt/main.go:112 +0x2cc
main.main()
	/Users/gokhanozeloglu/personal/pratt/main.go:28 +0x168
```

### The things should be considered:
* The user can write the expression without any space. --> `'2+4*12*2*442/12'`
* The user can add space for some operators while not adding space for others. --> `'2+ 4*12 *2*442/12'`
* The user can add more than 1 space. --> `'2 +         4 * 12 * 2 * 442 / 12'`
  * [`TrimSpace`](https://pkg.go.dev/strings#TrimSpace) method can be used.

I am here to fix this problem. I can write a helper function and split the given input string by operators(+,-,*,/). What do you think?

**Comment by juliaogris** [comment]
@gozeloglu - thanks for reporting this issue!

I've created this repo as the backing code base for the last section of a talk I intend to give at the GopherConAU in early November 2023. Here are the slides that go with it:
https://docs.google.com/presentation/d/1E2WmO4nWjhPNiXEWGBjXa2SblX8fODP7-Xjv6vpo9FA

This codebase is of course very incomplete as a real parser and especially thin on error handling. However, that's done on purpose. `pratt` is intended as a sketch and for education purposes only. I will make a note of this in the README.md. 

Please feel free to fork this code base or copy the bits you find useful and turn it into something more complete that suits you better, but as for this repo I would prefer not to add any additional features or complexity.

WRT to `go run ./main.go '2+4*12*2*442/12'` - the whole string `'2+4*12*2*442/12'` is considered a single operand, so the algorithm outputs it as is, just as it would output `2` for `go run ./main.go 2`.

**Comment by juliaogris** [comment]
I've added this paragraph to the README.md:

> pratt is intended for demonstration and education purposes only. It is purposefully thin on error handling. The input expression is expected to be a valid, using known operators only: <, +, -, *, /. Operators and operands must be separated by a single space, e.g. 1 + 2 * 3.

Please, let me know if this does not clarify things.

**Comment by gozeloglu** [comment]
Hi @juliaogris. I didn't know that this repository was backing your presentation. I assumed it has the purpose of being a complete tool. The README section is clear :ok_hand:. If I will find time, I will add more features to this tool by forking it. 

**Note:** By the way, your presentation seems pretty good, understandable, and instructive. I'd like to watch your presentation if it will be available on YouTube.

**Comment by juliaogris** [comment]
Thanks very much for the feedback on the presentation!
I will close this issue now - let me know if you end expanding on parser/lexer please.

**Comment by gozeloglu** [comment]
You're welcome @juliaogris. I did something on [this PR](https://github.com/gozeloglu/pratt/pull/1). I am planning to add new features. Thanks again.
